import type { IdentityRole } from '@prisma/client';

const capabilities: Record<IdentityRole, readonly string[]> = {
  patient: [
    'patient:self',
    'doctor:directory:read',
    'doctor:availability:read',
    'appointment:read',
    'appointment:create',
    'appointment:update',
    'appointment:cancel',
    'appointment:reschedule',
    'arrival:read',
    'arrival:record',
    'queue:patient-status:read',
    'notifications:read',
    'notifications:stream',
    'notifications:mark-read',
  ],
  receptionist: [
    'clinic:operations:read',
    'doctor:directory:read',
    'doctor:availability:read',
    'doctor:schedule:read',
    'appointment:read',
    'appointment:create',
    'appointment:update',
    'appointment:cancel',
    'appointment:reschedule',
    'arrival:read',
    'arrival:record',
    'queue:read',
    'queue:enqueue',
    'queue:open',
    'queue:pause',
    'queue:resume',
    'queue:close',
    'queue:call-next',
    'queue:recall',
    'queue:mark-no-response',
    'notifications:read',
    'notifications:stream',
    'notifications:mark-read',
  ],
  doctor: [
    'doctor:workspace:read',
    'doctor:directory:read',
    'doctor:availability:read',
    'doctor:schedule:read',
    'appointment:read',
    'arrival:read',
    'queue:read',
    'queue:open',
    'queue:pause',
    'queue:resume',
    'queue:call-next',
    'queue:consultation:start',
    'queue:consultation:complete',
    'notifications:read',
    'notifications:stream',
    'notifications:mark-read',
  ],
  clinicManager: [
    'clinic:management:read',
    'doctor:directory:read',
    'doctor:availability:read',
    'doctor:schedule:read',
    'clinic:hours:read',
    'appointment:read',
    'appointment:create',
    'appointment:update',
    'appointment:cancel',
    'appointment:reschedule',
    'arrival:read',
    'arrival:record',
    'queue:read',
    'queue:enqueue',
    'queue:open',
    'queue:pause',
    'queue:resume',
    'queue:close',
    'queue:call-next',
    'queue:recall',
    'queue:mark-no-response',
    'queue:consultation:start',
    'queue:consultation:complete',
    'notifications:read',
    'notifications:stream',
    'notifications:mark-read',
  ],
  platformAdministrator: [
    'platform:administration',
    'doctor:directory:read',
    'doctor:availability:read',
    'doctor:schedule:read',
    'clinic:hours:read',
    'appointment:read',
    'appointment:create',
    'appointment:update',
    'appointment:cancel',
    'appointment:reschedule',
    'arrival:read',
    'arrival:record',
    'queue:read',
  ],
};

export function capabilitiesFor(role: IdentityRole): ReadonlySet<string> {
  return new Set(capabilities[role]);
}
