import { describe, expect, it } from "vitest";
import { MockAppointmentRepository } from "@/features/appointments/data/mock-appointment-repository";
import { GetLiveQueue, OperateQueue } from "@/features/live-queue/application/operate-queue";
import { MockLiveQueueRepository } from "@/features/live-queue/data/mock-live-queue-repository";
import { queueHealth } from "@/features/live-queue/domain/queue-rules";

const clock={now:()=>new Date("2026-07-16T09:00:00.000Z")};
const service=(repository=new MockLiveQueueRepository())=>({repository,appointments:new MockAppointmentRepository(),operate:new OperateQueue(repository,new MockAppointmentRepository(),clock)});
const command=(operation:"open"|"pause"|"resume"|"callNext"|"recall"|"noResponse"|"complete",version=1,id:string=operation)=>({queueId:"queue-karwan",operation,expectedVersion:version,operationId:id});

describe("live queue operations",()=>{
 it("opens, pauses, and resumes through typed transitions",async()=>{const closed=new MockLiveQueueRepository("closed"),open=new OperateQueue(closed,new MockAppointmentRepository(),clock);expect((await open.execute(command("open"))).snapshot.lifecycle).toBe("open");const{operate}=service();const paused=await operate.execute(command("pause"));expect(paused.snapshot.lifecycle).toBe("paused");expect((await operate.execute(command("resume",paused.snapshot.version))).snapshot.lifecycle).toBe("open")});
 it("calls only the next eligible patient and completes the previous current",async()=>{const{operate}=service();const result=await operate.execute(command("callNext"));expect(result.snapshot.current?.name).toBe("Narin Omer");expect(result.snapshot.patients.filter(x=>x.state==="called"||x.state==="inConsultation")).toHaveLength(1);expect(result.snapshot.patients.find(x=>x.name==="Rojin Salih")?.state).toBe("completed")});
 it("recalls, records no response, and completes the current patient",async()=>{const recalled=service();expect((await recalled.operate.execute(command("recall"))).snapshot.current?.state).toBe("called");const missing=service();expect((await missing.operate.execute(command("noResponse"))).snapshot.current).toBeNull();const completed=service();expect((await completed.operate.execute(command("complete"))).snapshot.patients.find(x=>x.name==="Rojin Salih")?.state).toBe("completed")});
 it("is idempotent and rejects stale concurrent operations",async()=>{const{operate}=service(),input=command("callNext",1,"same-operation");const first=await operate.execute(input),again=await operate.execute(input);expect(again.idempotent).toBe(true);expect(again.snapshot.version).toBe(first.snapshot.version);await expect(operate.execute(command("recall",1,"stale-operation"))).rejects.toMatchObject({kind:"stale"})});
 it("rejects operations while paused and invalid repeated transitions",async()=>{const{operate}=service();const paused=await operate.execute(command("pause"));await expect(operate.execute(command("callNext",paused.snapshot.version,"blocked"))).rejects.toMatchObject({kind:"paused"});await expect(operate.execute(command("pause",paused.snapshot.version,"duplicate-pause"))).rejects.toMatchObject({kind:"notOpen"})});
 it("derives patient-friendly health from wait and delay",async()=>{const queue=await new MockLiveQueueRepository().get("queue-karwan");expect(queue&&queueHealth(queue)).toBe("busy");if(queue){queue.doctorDelayMinutes=18;expect(queueHealth(queue)).toBe("delayed");queue.doctorDelayMinutes=0;queue.averageWaitMinutes=5;queue.patients=queue.patients.slice(0,2);expect(queueHealth(queue)).toBe("healthy")}});
 it("propagates queue changes into appointment and patient-workspace reads",async()=>{const repository=new MockLiveQueueRepository(),appointments=new MockAppointmentRepository(),operate=new OperateQueue(repository,appointments,clock);const result=await operate.execute(command("callNext"));const current=await appointments.get("APT-305"),previous=await appointments.get("APT-302");expect(current?.appointment.status).toBe("waiting");expect(current?.appointment.arrival).toBe("waiting");expect(current?.queue.currentNumber).toBe(String(result.snapshot.currentNumber));expect(previous?.appointment.status).toBe("completed")});
 it("returns a snapshot with only the next three patients",async()=>{const view=await new GetLiveQueue(new MockLiveQueueRepository()).execute("queue-karwan");expect(view?.next).toHaveLength(3);expect(view?.waiting).toHaveLength(4)});
});
