import Link from "next/link";
import type { Dashboard } from "../domain/models";
import type { Locale, Messages } from "@/i18n";
import { fmt } from "@/i18n";

export function DashboardView({data,m,locale}:{data:Dashboard;m:Messages;locale:Locale}) {
 const queueStatus=(state:string,delay:number)=>state==="delayed"?fmt(m.late,{minutes:delay}):state==="paused"?m.paused:m.onTime;
 return <>
  <header className="heading"><p className="eyebrow">{data.clinic.name}</p><h1>{m.heading}</h1><p>{m.subheading}</p></header>
  <section className="clinic-status" aria-labelledby="clinic-status"><div className="status-lead"><span className="clinic-status-icon" aria-hidden="true"/><div><h2 id="clinic-status">{m.clinicOpen}</h2><p className="muted">{m.shift}</p></div></div><div className="clinic-timing"><span className="pill warning">{data.clinic.delayed?m.clinicDelayed:m.onTime}</span></div></section>
  <section className="metrics" aria-label={m.heading}>{[[m.todayAppointments,data.metrics.appointments],[m.waiting,data.metrics.waiting],[m.checkedIn,data.metrics.checkedIn],[m.delayedDoctors,data.metrics.delayed]].map(([label,value])=><div className="metric" key={label}><strong>{value}</strong><span>{label}</span></div>)}</section>
  <Section title={m.liveQueues} help={m.queueHelp}><Table heads={[m.doctor,m.current,m.waiting,m.delay,m.status,""]}>{data.queues.map((q,index)=><tr key={q.id} className={index===0?"priority-row":undefined}><td className="doctor-cell"><strong>{q.doctor}</strong></td><td><span className="queue-number">{q.current}</span></td><td className="numeric">{q.waiting}</td><td>{q.delay?fmt(m.late,{minutes:q.delay}):m.onTime}</td><td><span className={`pill ${q.state==="onTime"?"positive":q.state==="paused"?"neutral":"warning"}`}>{queueStatus(q.state,q.delay)}</span></td><td><Link className="link" href={`/${locale}/live-queue`}>{m.viewQueue}</Link></td></tr>)}</Table></Section>
  <Section title={m.nextArrivals} help={m.arrivalHelp}><Table heads={[m.time,m.patient,m.doctor,m.arrivalStatus,m.nextStep]}>{data.arrivals.map((a,index)=><tr key={a.id} className={index===0?"next-arrival":undefined}><td><time className="appointment-time">{a.time}</time></td><td className="patient-cell"><strong>{a.patient}</strong></td><td>{a.doctor}</td><td><span className={`pill ${a.status==="arrived"?"positive":"info"}`}>{a.status==="arrived"?m.arrived:m.expected}</span></td><td>{a.next==="welcome"?m.welcome:m.confirm}</td></tr>)}</Table></Section>
  <div className="lower"><Section title={m.doctorsWorking}><Table heads={[m.doctor,m.specialty,m.status,m.queueLoad,m.availability]}>{data.doctors.map(d=><tr key={d.id}><td className="doctor-cell"><strong>{d.name}</strong></td><td>{d.specialty}</td><td><span className={`pill ${d.state==="delayed"?"warning":d.state==="break"?"neutral":"positive"}`}>{d.state==="working"?m.working:d.state==="break"?m.break:d.state==="finished"?m.finished:m.clinicDelayed}</span></td><td>{fmt(m.count,{count:d.load})}</td><td className="numeric">{d.next}</td></tr>)}</Table></Section><Section title={m.updates} help={m.updatesHelp}><div className="updates">{data.updates.map((key,index)=><div className="update" key={key}><span className="update-marker" aria-hidden="true">{index+1}</span><span>{m[key as keyof Messages]}</span></div>)}</div></Section></div>
  <Section title={m.quick}><div className="quick"><Link href={`/${locale}/patients`}>{m.findPatient}</Link><Link href={`/${locale}/live-queue`}>{m.viewLiveQueue}</Link><Link href={`/${locale}/appointments`}>{m.todayAppointments}</Link></div></Section>
 </>;
}
function Section({title,help,children}:{title:string;help?:string;children:React.ReactNode}){return <section className="section"><div className="section-head"><div><h2>{title}</h2>{help&&<p>{help}</p>}</div></div>{children}</section>}
function Table({heads,children}:{heads:string[];children:React.ReactNode}){return <div className="table-wrap"><table><thead><tr>{heads.map((head,index)=><th key={index} scope="col">{head}</th>)}</tr></thead><tbody>{children}</tbody></table></div>}
