"use client";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { useState } from "react";
import type { Locale, Messages } from "@/i18n";
import { doctorMessages } from "@/features/doctor/presentation/messages";
import { roleEntryMessages } from "@/features/doctor/presentation/role-entry-messages";
import { DoctorShell } from "./doctor-shell";
export function Shell({locale,m,children,allowDoctorEntry=false}:{locale:Locale;m:Messages;children:React.ReactNode;allowDoctorEntry?:boolean}){
 const path=usePathname();const[open,setOpen]=useState(false);const items=[["dashboard",m.dashboard],["patients",m.patients],["appointments",m.appointments],["live-queue",m.queue],["doctors",m.doctors],["schedule",m.schedule],["notifications",m.notifications],["settings",m.settings]];
 if(path.startsWith(`/${locale}/doctor`))return <div className="doctor-role-boundary">{allowDoctorEntry&&<Link className="role-entry doctor-role-entry" href={`/${locale}/dashboard`}>{roleEntryMessages(locale).returnReceptionist}</Link>}<DoctorShell locale={locale} m={doctorMessages(locale)}>{children}</DoctorShell></div>;
 return <div className="portal"><a className="skip" href="#main">{m.skip}</a><aside className={`sidebar ${open?"open":""}`} aria-label={m.app}><div className="brand"><span className="mark">S</span><div className="brand-copy"><strong>Saxlem</strong><small>Medical Center</small></div></div><nav className="nav">{items.map(([slug,label],index)=><Link onClick={()=>setOpen(false)} key={slug} href={`/${locale}/${slug}`} aria-current={path.endsWith(slug)?"page":undefined}><span className="nav-symbol" aria-hidden="true">{index+1}</span><span className="nav-label">{label}</span></Link>)}</nav><div className="identity"><span className="avatar">SA</span><div><strong>Sara Ahmed</strong><small>{m.receptionist}</small></div></div></aside><div className="workspace"><header className="topbar"><button className="control menu" aria-expanded={open} aria-label={m.openMenu} onClick={()=>setOpen(!open)}><span className="menu-glyph" aria-hidden="true"/></button><div className="top-clinic"><span className="top-clinic-mark">S</span><div><strong>Saxlem Medical Center</strong><small>{m.shift}</small></div></div><div className="top-actions">{allowDoctorEntry&&<Link className="role-entry" href={`/${locale}/doctor/session`}>{roleEntryMessages(locale).openDoctor}</Link>}<Link className="control notification-control" aria-label={m.openNotifications} href={`/${locale}/notifications`}><span aria-hidden="true">N</span></Link><LocaleLinks locale={locale} label={m.language}/><div className="top-identity"><span className="avatar">SA</span><div><strong>Sara Ahmed</strong><small>{m.receptionist}</small></div></div></div></header><main id="main" className="main">{children}</main></div></div>;
}
function LocaleLinks({locale,label}:{locale:Locale;label:string}){const path=usePathname();return <div className="locale-group" aria-label={label}>{(["en","ar","ku"] as const).map(l=><Link className="locale-link" key={l} aria-current={l===locale?"true":undefined} href={path.replace(`/${locale}/`,`/${l}/`)}>{l.toUpperCase()}</Link>)}</div>}
