import type { Locale } from "@/i18n";

const en = {
  appointments: "Appointments", appointmentHelp: "Review and manage clinic appointments.", patients: "Patient lookup", patientHelp: "Search securely by name, phone number, or patient ID.",
  from: "From", to: "To", status: "Status", allStatuses: "All statuses", apply: "Apply filters", date: "Date and time", patient: "Patient", doctor: "Doctor", clinic: "Clinic", reason: "Reason", duration: "Duration", fee: "Fee", reference: "Appointment ID", actions: "Actions", view: "View appointment", previous: "Previous", next: "Next page", noAppointments: "No appointments match these filters.",
  dateRangeInvalid: "Choose real dates and make sure From is not after To.",
  scheduled: "Scheduled", confirmed: "Confirmed", cancelled: "Cancelled", completed: "Completed", noShow: "No show", appointmentDetails: "Appointment details", backAppointments: "Back to appointments", cancel: "Cancel appointment", reschedule: "Reschedule appointment", cancelTitle: "Cancel this appointment?", cancelHelp: "Explain the reason. This action cannot be undone.", rescheduleTitle: "Reschedule appointment", startsAt: "New date and time", minutes: "Duration in minutes", close: "Close", confirmAction: "Confirm", saving: "Saving…", success: "Appointment updated.", validation: "Check the information and try again.", conflict: "The appointment changed. Refresh before trying again.",
  search: "Search", searchAction: "Search patients", searchHint: "Enter at least 2 characters", noPatients: "No patients match your search.", searchFirst: "Enter a name, phone number, or patient ID to begin.", patientDetails: "Patient details", active: "Active", inactive: "Inactive", upcoming: "Upcoming appointments", recent: "Recent appointments", noUpcoming: "No upcoming appointments.", noRecent: "No recent appointments.", openAppointment: "Open appointment", backPatients: "Back to patient lookup",
  loading: "Loading…", offline: "The backend cannot be reached. Check the connection and try again.", unauthorized: "Your session has expired. Sign in again.", forbidden: "You do not have access to this clinic information.", notFound: "The requested record was not found.", backendError: "The service could not complete the request.", retry: "Try again",
};
export type ClinicalMessages = typeof en;
const ar: ClinicalMessages = {appointments:"المواعيد",appointmentHelp:"راجع مواعيد العيادة وأدرها.",patients:"البحث عن مريض",patientHelp:"ابحث بأمان بالاسم أو رقم الهاتف أو رقم المريض.",from:"من",to:"إلى",status:"الحالة",allStatuses:"كل الحالات",apply:"تطبيق عوامل التصفية",date:"التاريخ والوقت",patient:"المريض",doctor:"الطبيب",clinic:"العيادة",reason:"السبب",duration:"المدة",fee:"الأجرة",reference:"رقم الموعد",actions:"الإجراء",view:"عرض الموعد",previous:"السابق",next:"الصفحة التالية",noAppointments:"لا توجد مواعيد مطابقة.",dateRangeInvalid:"معلومات",scheduled:"معلومات",confirmed:"مؤكد",cancelled:"ملغى",completed:"مكتمل",noShow:"لم يحضر",appointmentDetails:"تفاصيل الموعد",backAppointments:"العودة إلى المواعيد",cancel:"إلغاء الموعد",reschedule:"تغيير الموعد",cancelTitle:"هل تريد إلغاء الموعد؟",cancelHelp:"اكتب السبب. لا يمكن التراجع عن هذا الإجراء.",rescheduleTitle:"تغيير الموعد",startsAt:"التاريخ والوقت الجديدان",minutes:"المدة بالدقائق",close:"إغلاق",confirmAction:"تأكيد",saving:"جارٍ الحفظ…",success:"تم تحديث الموعد",validation:"راجع المعلومات وحاول مجدداً.",conflict:"تم تغيير الموعد. حدّث الصفحة قبل المحاولة.",search:"بحث",searchAction:"البحث عن المرضى",searchHint:"أدخل حرفين على الأقل",noPatients:"لا يوجد مرضى مطابقون للبحث.",searchFirst:"أدخل اسماً أو رقم هاتف أو رقم مريض للبدء.",patientDetails:"تفاصيل المريض",active:"نشط",inactive:"غير نشط",upcoming:"المواعيد القادمة",recent:"المواعيد السابقة",noUpcoming:"لا توجد مواعيد قادمة",noRecent:"لا توجد مواعيد سابقة.",openAppointment:"فتح الموعد",backPatients:"العودة إلى بحث المرضى",loading:"جارٍ التحميل…",offline:"تعذر الاتصال بالخدمة. تحقق من الاتصال وحاول مجدداً.",unauthorized:"انتهت الجلسة. سجّل الدخول مجدداً.",forbidden:"ليس لديك صلاحية لعرض معلومات هذه العيادة.",notFound:"لم يتم العثور على السجل المطلوب.",backendError:"تعذر على الخدمة إكمال الطلب.",retry:"حاول مجدداً"};
const ku: ClinicalMessages = {appointments:"ژڤان",appointmentHelp:"ژوانێن کلینیکێ ببینە و ڕێک بخە.",patients:"لێگەڕین ل نەخۆشی",patientHelp:"ب پاراستی ب ناڤ، ژمارا تەلەفونێ یان ژمارا نەخۆشی بگەڕێ.",from:"ژ",to:"هەتا",status:"رەوش",allStatuses:"هەمی دۆخ",apply:"جوداکرنێ جێبەجێ بکە",date:"ڕێکەوت و دەم",patient:"نەخوش",doctor:"نوژدار",clinic:"کلینیک",reason:"ئەگەر",duration:"مایی",fee:"کرێ",reference:"ژمارا ژڤانێ",actions:"کار",view:"ژوانی ببینە",previous:"پێشتر",next:"لاپەڕا پاش",noAppointments:"هیچ ژوانەک گونجای نەهاتە دیتن.",dateRangeInvalid:"رێکەفتێن دروست ب هەلبژێرە و پشتراست بکە رێکەفتا دەستپێکێ پشتی رێکەفتا دووماهیێ نەبیت",scheduled:"زانیاری",confirmed:"پشتڕاستکری",cancelled:"هەلوەشای",completed:"تەمامبووی",noShow:"نەهات",appointmentDetails:"هویرکاتیێن ژڤانێ",backAppointments:"ڤەگەڕە ژوانان",cancel:"ژوانی هەلوەشێنە",reschedule:"دەمێ ژڤانێ بگهورە",cancelTitle:"ژوانی هەلوەشێنی؟",cancelHelp:"ئەگەری بنڤیسە. ئەڤ کارە ناهێتە ڤەگەڕاندن.",rescheduleTitle:"دەمێ ژڤانێ بگهورە",startsAt:"رێکەفت و دەمێ نوی",minutes:"ماوە ب خولەکان",close:"بگرە",confirmAction:"پشتراست بکە",saving:"دهێتە پاراستن…",success:"ژڤان هاتە نویکرن",validation:"زانیارییان بپشکنە و دیسان هەول بدە",conflict:"ژوان هاتیە گوهۆڕین. لاپەڕێ نوو بکە.",search:"لێ بگەرە",searchAction:"ل نەخوشان بگەرە",searchHint:"کێمترین دوو پیتان بنڤیسە",noPatients:"چ نەخوش ل گەل لێگەریانا تە ناگونجن",searchFirst:"ناڤ، ژمارا تەلەفونێ یان ژمارا نەخۆشی بنڤیسە.",patientDetails:"هویرکاتیێن نەخوشی",active:"چالاک",inactive:"نەچالاک",upcoming:"ژڤانێن داهاتی",recent:"ژوانێن بۆری",noUpcoming:"چ ژڤان ل دویفرا نینن",noRecent:"ژوانێن بۆری نینن.",openAppointment:"ژڤانی ڤەکە",backPatients:"ڤەگەڕە لێگەڕینا نەخۆشان",loading:"دهێتە بارکرن…",offline:"خزمەت ناهێتە گەهشتن. پەیوەندیێ بپشکنە.",unauthorized:"دانیشتن دووماهی هات. دیسان بچۆ ژوور.",forbidden:"دەستهەلاتا دیتنا زانیاریێن ڤێ کلینیکێ نینە.",notFound:"تۆمار نەهاتە دیتن.",backendError:"خزمەتێ نەشیا داخوازیێ تەمام بکەت.",retry:"دیسان هەول بدە"};
export const clinicalMessages = (locale: Locale): ClinicalMessages => ({ en, ar, ku })[locale];
